# ---- Build time: 540s
# ---- Build size: 10.4GB
FROM node:18-slim
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app

# build with
# docker build \
#   --build-arg COMMIT=$(git rev-parse HEAD) \
#   --build-arg VECTOR_TILE_URL=<url of the vector service> \
#   --build-arg MAPTILER_STYLE_KEY=<maptiler style key> \
#   --build-arg ADFS_ID=<adfs client id> \
#   --build-arg ADFS_SECRET=<adfs secret> \
#   --build-arg ADFS_ISSUER=<adfs issuer> \
#   --build-arg NEXTAUTH_SECRET=<nextauth secret> \
#   --build-arg NEXTAUTH_URL=<nextauth url>
ARG COMMIT
ARG VECTOR_TILE_URL
ARG MAPTILER_STYLE_KEY
ARG ADFS_ID
ARG ADFS_SECRET
ARG ADFS_ISSUER
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG SENTRY_DSN
ARG SENTRY_ORG

# Build app
COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node app/package.json ./app/
RUN yarn install --frozen-lockfile

ENV NODE_ENV production
ENV NODE_OPTIONS=--max_old_space_size=2048
ENV NEXT_PUBLIC_COMMIT=$COMMIT
ENV NEXT_PUBLIC_BASE_VECTOR_TILE_URL=$VECTOR_TILE_URL
ENV NEXT_PUBLIC_MAPTILER_STYLE_KEY=$MAPTILER_STYLE_KEY
ENV ADFS_ID=$ADFS_ID
ENV ADFS_SECRET=$ADFS_SECRET
ENV ADFS_ISSUER=$ADFS_ISSUER
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_TELEMETRY_DISABLED=1
ENV SENTRY_DSN=$SENTRY_DSN
ENV SENTRY_ORG=$SENTRY_ORG
ENV GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=
ENV NO_PROXY='localhost,127.0.0.1'
ENV PORT 3000

COPY ./ ./

RUN yarn prisma generate
RUN yarn build


# Install only prod dependencies and start app
RUN yarn install --frozen-lockfile --production && yarn cache clean

USER node

EXPOSE 3000

#CMD npm start

# Handles signals properly, but doesn't work here
CMD ["node", "app/.next/standalone/app/server.js", "--port", "3000"]
