
DROP TABLE IF EXISTS config;

CREATE TABLE config (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key           character(12) UNIQUE NOT NULL,
  data          jsonb,
  created_at    timestamp NOT NULL DEFAULT NOW()
);