name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  base-checks:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        job: [lint, typecheck, test, knip]
    steps:
      - uses: actions/checkout@v7
      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn install --immutable --prefer-offline
      - run: yarn lingui compile
      - run: yarn ${{ matrix.job }}
