name: GitLab Mirror Test

on: [push, delete]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Logging
        run: |
          git remote show origin
          git for-each-ref
      - name: Mirror to GitLab
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://gitlab.ldbar.ch/interactivethings/visualize-mirroring-test.git
          DEBUG: "true"
          GIT_USERNAME: gitlab+deploy-token-8
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD_TEST }}
