name: GitLab Mirror Test

on: [push, delete]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Logging
        run: |
          git remote show origin
          git for-each-ref
      - name: Mirror to GitLab
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_TEST_PKEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.GITLAB_TEST_HOSTS }}
        with:
          source-repo: "git@github.com:visualize-admin/visualization-tool.git"
          destination-repo: "git@gitlab.ldbar.ch:interactivethings/visualize-mirroring-test.git"
